{% set name = "tabmat" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 100b789e953d672cb839ec60ad24b7acd272f3dad9fb48b80596edfe0e8210ac

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  script_env:
    - GLM_ARCHITECTURE=default
    - JEMALLOC_SYS_WITH_LG_PAGE=16  # [linux-aarch64]
  # ignore_run_exports:
  #   - libcxx
  #   - numpy

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - wheel
    - mako
    - numpy {{ numpy }}
    - cython !=3.0.4
    - jemalloc {{ jemalloc }}  # [not win]
    - xsimd <11|>12.1
    - llvm-openmp {{ llvm_openmp }} # [osx]
    - libgomp  # [linux]
  run:
    - python
    - formulaic >=0.6
    - narwhals >=2.0
    - numpy
    - scipy
    - llvm-openmp  # [osx]
    - libgomp  # [linux]

# E       Arrays are not equal
# E        ACTUAL: array([[1., 1., 0., ..., 0., 0., 0.],
# E        DESIRED: array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
# E               0., 0., 0., 0., 0., 0., 0., 0.],
{% set deselect_tests = " --deselect=tests/test_formula.py::test_matrix_against_native" %}

test:
  source_files:
    - tests
  imports:
    - tabmat
  requires:
    - pip
    - pytest
    - polars
    - click
    - pyarrow
  commands:
    - pip check
    - pytest -v tests {{ deselect_tests }}

about:
  home: https://github.com/Quantco/tabmat
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Efficient matrix representations for working with tabular data
  description: |
    tabmat provides efficient tools for representing tabular data as a mix of
    dense, sparse and categorical subcomponents, resulting in 100x faster 
    performance on some machine learning problems!
  doc_url: https://tabmat.readthedocs.io
  dev_url: https://github.com/Quantco/tabmat

extra:
  recipe-maintainers:
    - MatthiasSchmidtblaicherQC
    - MarcAntoineSchmidtQC
    - xhochy
    - stanmart
    - jtilly
